import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Avatar, Box, Button, Flex, Heading, HStack, IconButton, Menu, MenuButton, MenuItem, MenuList, Spacer, Tooltip, } from '@chakra-ui/react';
import { FaHome, FaPlusSquare, FaUser } from 'react-icons/fa';
import { IoNotificationsOutline } from 'react-icons/io5';
import { TbRefresh } from 'react-icons/tb';
const DesktopBar = ({ bg, borderColor, textColor, userProfilePic, uploading, onHome, onUpload, onRefresh, onProfile, onLogout, notifications, }) => {
    return (_jsxs(_Fragment, { children: [_jsxs(Flex, { display: { base: 'none', md: 'flex' }, position: "fixed", top: 0, left: 0, right: 0, height: "64px", bg: bg, borderBottomWidth: "1px", borderColor: borderColor, align: "center", px: 4, zIndex: 1000, children: [_jsx(HStack, { spacing: 3, cursor: "pointer", onClick: onHome, children: _jsx(Heading, { size: "md", color: textColor, fontFamily: "cursive", children: "EsteCla" }) }), _jsx(Spacer, {}), _jsxs(HStack, { spacing: 2, children: [_jsx(Tooltip, { label: "Home", children: _jsx(IconButton, { "aria-label": "Home", icon: _jsx(FaHome, {}), variant: "ghost", onClick: onHome }) }), _jsx(Tooltip, { label: "Upload", children: _jsx(IconButton, { "aria-label": "Upload", icon: _jsx(FaPlusSquare, {}), variant: "ghost", onClick: onUpload, isDisabled: uploading }) }), _jsx(Tooltip, { label: "Refresh", children: _jsx(IconButton, { "aria-label": "Refresh", icon: _jsx(TbRefresh, {}), variant: "ghost", onClick: onRefresh }) }), notifications && (_jsx(Tooltip, { label: "Notifiche", children: _jsxs(Box, { position: "relative", children: [_jsx(IconButton, { "aria-label": `Notifiche${notifications.count ? `, ${notifications.count} non lette` : ''}`, icon: _jsx(IoNotificationsOutline, {}), variant: "ghost", onClick: notifications.onOpen }), notifications.count > 0 && (_jsx(Box, { position: "absolute", top: 1, right: 1, bg: "red.500", color: "white", borderRadius: "full", fontSize: "10px", minW: "16px", h: "16px", display: "flex", alignItems: "center", justifyContent: "center", px: 1, "aria-live": "polite", "aria-atomic": "true", children: notifications.count > 9 ? '9+' : notifications.count }))] }) })), _jsxs(Menu, { children: [_jsx(MenuButton, { as: Button, variant: "ghost", p: 0, minW: 0, "aria-label": "User menu", children: _jsx(Avatar, { size: "sm", src: userProfilePic }) }), _jsxs(MenuList, { children: [_jsx(MenuItem, { icon: _jsx(FaUser, {}), onClick: onProfile, children: "Profilo" }), _jsx(MenuItem, { onClick: onLogout, children: "Logout" })] })] })] })] }), _jsx(Box, { display: { base: 'none', md: 'block' }, height: "64px" })] }));
};
export default DesktopBar;
