import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Flex, IconButton, Avatar } from '@chakra-ui/react';
import { FaHome, FaPlusSquare } from 'react-icons/fa';
import { TbRefresh } from 'react-icons/tb';
import { IoNotificationsOutline } from 'react-icons/io5';
const MobileBar = ({ bg, borderColor, uploading, onHome, onUpload, onRefresh, onProfile, userProfilePic, notifications, }) => {
    return (_jsxs(Flex, { as: "nav", "aria-label": "Barra di navigazione mobile", display: { base: 'flex', md: 'none' }, position: "fixed", bottom: 0, left: 0, right: 0, height: "88px", bg: bg, borderTopWidth: "1px", borderColor: borderColor, align: "flex-start", justify: "space-around", px: 3, pt: 2, zIndex: 1400, pb: "calc(env(safe-area-inset-bottom) + 12px)", overflow: "hidden", children: [_jsx(IconButton, { "aria-label": "Home", icon: _jsx(FaHome, {}), variant: "ghost", size: "lg", fontSize: "28px", onClick: onHome }), _jsx(IconButton, { "aria-label": "Refresh", icon: _jsx(TbRefresh, {}), variant: "ghost", size: "lg", fontSize: "28px", onClick: onRefresh }), _jsx(IconButton, { "aria-label": "Upload", icon: _jsx(FaPlusSquare, {}), variant: "solid", colorScheme: "blue", boxShadow: "0 8px 20px rgba(0,0,0,0.25)", borderRadius: "full", size: "lg", fontSize: "28px", onClick: onUpload, isLoading: uploading }), notifications && (_jsxs(Box, { position: "relative", children: [_jsx(IconButton, { "aria-label": `Notifiche${notifications.count ? `, ${notifications.count} non lette` : ''}`, icon: _jsx(IoNotificationsOutline, {}), variant: "ghost", size: "lg", fontSize: "28px", onClick: notifications.onOpen }), notifications.count > 0 && (_jsx(Box, { position: "absolute", top: 1, right: 1, bg: "red.500", color: "white", borderRadius: "full", fontSize: "10px", minW: "16px", h: "16px", display: "flex", alignItems: "center", justifyContent: "center", px: 1, "aria-live": "polite", "aria-atomic": "true", children: notifications.count > 9 ? '9+' : notifications.count }))] })), _jsx(Box, { as: "button", "aria-label": "Profilo", onClick: onProfile, bg: "none", border: "none", p: 0, m: 0, display: "flex", alignItems: "center", justifyContent: "center", height: "48px", width: "48px", borderRadius: "full", _focus: { boxShadow: 'outline' }, children: _jsx(Avatar, { size: "md", name: "Profilo", src: userProfilePic || undefined, bg: "gray.200" }) })] }));
};
export default MobileBar;
