name: Deploy to Firebase

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.github/**'

env:
  CI: true # Force production mode

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run ESLint
        run: npm run lint

      - name: Type Check (TS)
        run: |
          if grep -q '"typescript"' package.json; then
            npm run type-check
          fi

      # - name: Run tests
      #   run: npm test -- --watchAll=false

  build:
    name: Build Production
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: production-build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESTECLA_UNIVERSE }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
          target: 'production'
